"""
Builds/refreshes analyzers/<family>/golden/manifest.json - a checksummed index of the golden
test-data set, so we can detect silent edits, corruption, or accidental additions/removals,
and record where each doc came from.

Usage:
  python build-golden-manifest.py <family>     # e.g. invoiceHeader
  python build-golden-manifest.py --all

Writes: analyzers/<family>/golden/manifest.json
"""
import argparse
import hashlib
import json
import os

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
ANALYZERS_DIR = os.path.join(REPO_ROOT, "analyzers")


def sha256_of(path):
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for chunk in iter(lambda: f.read(65536), b""):
            h.update(chunk)
    return h.hexdigest()


def build_manifest_for_family(family):
    golden_dir = os.path.join(ANALYZERS_DIR, family, "golden")
    if not os.path.isdir(golden_dir):
        raise FileNotFoundError(f"No golden/ folder for family '{family}' at {golden_dir}")

    pdfs = sorted(f for f in os.listdir(golden_dir) if f.lower().endswith(".pdf"))

    docs = []
    for pdf_name in pdfs:
        base = os.path.splitext(pdf_name)[0]
        pdf_path = os.path.join(golden_dir, pdf_name)
        expected_name = f"{base}.expected.json"
        expected_path = os.path.join(golden_dir, expected_name)

        if not os.path.exists(expected_path):
            print(f"  WARNING: {pdf_name} has no matching {expected_name} - skipping")
            continue

        docs.append({
            "name": base,
            "pdf": pdf_name,
            "expected": expected_name,
            "pdfSha256": sha256_of(pdf_path),
            "expectedSha256": sha256_of(expected_path),
            # Manually-verified ground truth (created/checked by a human independent of any
            # generator) is stronger evidence than template-generated ground truth. Defaults to
            # "generated"; change to "human-verified" once someone has reviewed a doc's expected.json
            # against the actual source document.
            "groundTruthSource": "generated",
        })

    manifest = {
        "family": family,
        "note": (
            "Auto-generated by build-golden-manifest.py. Re-run it after adding/removing/editing "
            "golden docs so checksums stay accurate. groundTruthSource is NOT auto-detected - update "
            "it by hand when a doc's expected.json has been independently verified."
        ),
        "documentCount": len(docs),
        "documents": docs,
    }

    out_path = os.path.join(golden_dir, "manifest.json")
    with open(out_path, "w", encoding="utf-8") as f:
        json.dump(manifest, f, indent=2)

    print(f"Wrote {out_path} ({len(docs)} documents)")
    return out_path


def all_families():
    return sorted(
        name for name in os.listdir(ANALYZERS_DIR)
        if os.path.isdir(os.path.join(ANALYZERS_DIR, name, "golden"))
    )


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("family", nargs="?", help="Analyzer family folder name, e.g. invoiceHeader")
    parser.add_argument("--all", action="store_true", help="Build for every family under analyzers/")
    args = parser.parse_args()

    if args.all:
        for family in all_families():
            build_manifest_for_family(family)
    elif args.family:
        build_manifest_for_family(args.family)
    else:
        parser.error("Provide a family name or --all")


if __name__ == "__main__":
    main()
