<#
.SYNOPSIS
  Builds/refreshes analyzers/<family>/golden/manifest.json - a checksummed index of the golden
  test-data set.

.DESCRIPTION
  Detects silent edits, corruption, or accidental additions/removals in the golden set, and
  records where each doc came from via a "groundTruthSource" flag. Golden documents are not
  limited to PDF - any format Content Understanding's document analyzer accepts (DOCX, XLSX,
  PPTX, images, and more; see scripts/lib/GoldenDocs.ps1) is indexed.

.PARAMETER Family
  Analyzer family folder name, e.g. invoice.

.PARAMETER All
  Build for every family under analyzers/.

.EXAMPLE
  ./build-golden-manifest.ps1 -Family invoice

.EXAMPLE
  ./build-golden-manifest.ps1 -All

.NOTES
  Writes: analyzers/<family>/golden/manifest.json
#>
param(
  [string]$Family,
  [switch]$All
)

$ErrorActionPreference = "Stop"
$repoRoot = Resolve-Path (Join-Path $PSScriptRoot "..")
$analyzersDir = Join-Path $repoRoot "analyzers"

. (Join-Path $PSScriptRoot ".." "scripts" "lib" "GoldenDocs.ps1")

if (-not $All -and -not $Family) {
  Write-Error "Provide -Family <name> or -All"
  exit 2
}

function Get-AllFamilies {
  Get-ChildItem $analyzersDir -Directory |
    Where-Object { $_.Name -notlike "_*" } |
    Where-Object { Test-Path (Join-Path $_.FullName "golden") } |
    ForEach-Object { $_.Name } |
    Sort-Object
}

function Get-Sha256 {
  param([string]$Path)
  (Get-FileHash -Path $Path -Algorithm SHA256).Hash.ToLower()
}

function Build-ManifestForFamily {
  param([string]$FamilyName)

  $goldenDir = Join-Path $analyzersDir $FamilyName "golden"
  if (-not (Test-Path $goldenDir)) {
    throw "No golden/ folder for family '$FamilyName' at $goldenDir"
  }

  $sourceDocs = Get-GoldenDocFiles -GoldenDir $goldenDir

  $docs = @()
  foreach ($sourceDoc in $sourceDocs) {
    $base = [System.IO.Path]::GetFileNameWithoutExtension($sourceDoc.Name)
    $expectedName = "$base.expected.json"
    $expectedPath = Join-Path $goldenDir $expectedName

    if (-not (Test-Path $expectedPath)) {
      Write-Host "  WARNING: $($sourceDoc.Name) has no matching $expectedName - skipping"
      continue
    }

    $docs += [ordered]@{
      name           = $base
      file           = $sourceDoc.Name
      expected       = $expectedName
      fileSha256     = Get-Sha256 -Path $sourceDoc.FullName
      expectedSha256 = Get-Sha256 -Path $expectedPath
      # Manually-verified ground truth (created/checked by a human independent of any
      # generator) is stronger evidence than template-generated ground truth. Defaults to
      # "generated"; change to "human-verified" once someone has reviewed a doc's expected.json
      # against the actual source document.
      groundTruthSource = "generated"
    }
  }

  $manifest = [ordered]@{
    family = $FamilyName
    note = "Auto-generated by build-golden-manifest.ps1. Re-run it after adding/removing/editing golden docs so checksums stay accurate. groundTruthSource is NOT auto-detected - update it by hand when a doc's expected.json has been independently verified."
    documentCount = $docs.Count
    documents = $docs
  }

  $outPath = Join-Path $goldenDir "manifest.json"
  ($manifest | ConvertTo-Json -Depth 10) | Set-Content -Path $outPath -Encoding utf8

  Write-Host "Wrote $outPath ($($docs.Count) documents)"
  return $outPath
}

$families = if ($All) { Get-AllFamilies } else { @($Family) }

foreach ($f in $families) {
  Build-ManifestForFamily -FamilyName $f | Out-Null
}
